// <auto-generated />
using System;
using Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infra.Migrations
{
    [DbContext(typeof(SeriesCatalogDbContext))]
    [Migration("20250723143951_SeedInitialSeries")]
    partial class SeedInitialSeries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Domain.Entities.Serie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Seasons")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Series");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bde9c541-2d22-4e9e-b531-61fd747bae3d"),
                            Genre = "[\"Fantasy\"]",
                            Seasons = 9,
                            Title = "Game of Thrones"
                        },
                        new
                        {
                            Id = new Guid("e2fb83cf-37e2-4c06-9939-389e7ca2d2de"),
                            Genre = "[\"Crime\"]",
                            Seasons = 5,
                            Title = "Breaking Bad"
                        },
                        new
                        {
                            Id = new Guid("f0724150-cd9c-4b69-a02b-441af370e4e7"),
                            Genre = "[\"Sci-Fi\"]",
                            Seasons = 4,
                            Title = "Stranger Things"
                        },
                        new
                        {
                            Id = new Guid("527527a4-7afe-4bb2-beb9-eb7882a21581"),
                            Genre = "[\"Drama\"]",
                            Seasons = 6,
                            Title = "The Crown"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
